version: 2
jobs:
  build:
    working_directory: ~/run-plotter
    docker:
      - image: circleci/clojure:lein-2.9.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m # limit the maximum heap size to prevent out of memory errors
    steps:
      - checkout
      - restore_cache:
          key: run-plotter-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: run-plotter-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/run-plotter.jar
          destination: uberjar
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t run-plotter .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push ariv3ra/$IMAGE_NAME:$TAG