version: 2
jobs:
  build:
    working_directory: ~/run-plotter
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1-node
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m # limit the maximum heap size to prevent out of memory errors
    steps:
      - checkout
      - restore_cache:
          key: run-plotter-{{ checksum "project.clj" }}
      - run:
          name: Build clojurescript
          command: |
            npm install
            npx shadow-cljs release app
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: run-plotter-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
      - run:
          name: Deploy jar to heroku
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            heroku plugins:install java
            heroku stack:set heroku-18 --app run-plotter
            heroku deploy:jar target/*-standalone.jar --app run-plotter
